// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Joseph Folayan",
            "email": "folayanjoey@gmail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/save/news": {
            "get": {
                "description": "Saves news articles stored in a redis cache into a mongo collection",
                "produces": [
                    "application/json"
                ],
                "summary": "Save News",
                "responses": {
                    "200": {
                        "description": "News scrapped and added to cache",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/scrape/news": {
            "get": {
                "description": "Makes a get request to newsapi.io and cahes news objects in database",
                "produces": [
                    "application/json"
                ],
                "summary": "Scrape News",
                "responses": {
                    "200": {
                        "description": "News scrapped and added to cache",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "http://51.21.106.236:8001",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "News Aggregator service",
	Description:      "This service scrapes for news articles and stores in a mongo db the news aggregator system",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
